languageCode = "en"
languageName = "English"
weight = 1
title = "tsssni's blowfish blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "tsssni's blowfish blog"

[author]
image = "plana-profile.png"
name = "tsssni"
headline = "何気ない日常で、ほんの少しの奇跡を見つける物語。"
bio = "I'm non-physically based."
links = [ { github = "https://github.com/tsssni" } ]
