[[main]]
none = "none"

[[main]]
name = "关于"
pageRef = "about/1717500731146-about"
identifier = "PmJ4BvEkD5"
weight = 4

[[main]]
name = "ACGN"
pageRef = "acgn"
identifier = "SEoPcFKwGx"
weight = 3

[[main]]
name = "Unix"
pageRef = "unix"
identifier = "V1iSLuNBw3"
weight = 2

[[main]]
name = "渲染"
pageRef = "render"
identifier = "0keUXICnJM"
weight = 1

[[footer]]
none = "none"
