[[main]]
none = "none"

[[main]]
name = "关于"
pageRef = "about/about"
identifier = "PmJ4BvEkD5"
weight = 5

[[main]]
name = "ACGN"
pageRef = "acgn"
identifier = "SEoPcFKwGx"
weight = 4

[[main]]
name = "UNIX"
pageRef = "unix"
identifier = "V1iSLuNBw3"
weight = 3

[[main]]
name = "数学"
pageRef = "maths"
identifier = "u1uXYnUUPG"
weight = 2

[[main]]
name = "渲染"
pageRef = "render"
identifier = "0keUXICnJM"
weight = 1

[[footer]]
none = "none"
