[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about/1717500731146-about"
identifier = "PmJ4BvEkD5"
weight = 2

[[main]]
name = "Unix"
pageRef = "unix"
identifier = "V1iSLuNBw3"
weight = 1

[[footer]]
none = "none"
