[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about/1717500731146-about"
identifier = "PmJ4BvEkD5"
weight = 3

[[main]]
name = "Unix"
pageRef = "unix"
identifier = "V1iSLuNBw3"
weight = 1

[[main]]
name = "ACGN"
pageRef = "acgn"
identifier = "SEoPcFKwGx"
weight = 2

[[footer]]
none = "none"
