name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install
        uses: DeterminateSystems/nix-installer-action@v18

      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Depend
        run: nix develop -c npm install

      - name: Build
        run: nix develop -c node scripts/build.mjs --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
